<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="5" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="1177" started-at="2016-05-29T17:11:43Z" finished-at="2016-05-29T17:11:44Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="1177" started-at="2016-05-29T17:11:43Z" finished-at="2016-05-29T17:11:44Z">
      <class name="com.github.grzesiek_galezowski.test_environment.XAssertSpecification">
        <test-method status="PASS" signature="shouldAssertOnValueObjectBehavior()[pri:0, instance:com.github.grzesiek_galezowski.test_environment.XAssertSpecification@3a4afd8d]" name="shouldAssertOnValueObjectBehavior" duration-ms="583" started-at="2016-05-29T19:11:43Z" finished-at="2016-05-29T19:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldAssertOnValueObjectBehavior -->
        <test-method status="PASS" signature="shouldAssertOnValueObjectBehaviorWithFluentSyntax()[pri:0, instance:com.github.grzesiek_galezowski.test_environment.XAssertSpecification@3a4afd8d]" name="shouldAssertOnValueObjectBehaviorWithFluentSyntax" duration-ms="199" started-at="2016-05-29T19:11:43Z" finished-at="2016-05-29T19:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldAssertOnValueObjectBehaviorWithFluentSyntax -->
        <test-method status="PASS" signature="shouldFailWhenAssertingThatNoExceptionShouldBeThrownButThereIs()[pri:0, instance:com.github.grzesiek_galezowski.test_environment.XAssertSpecification@3a4afd8d]" name="shouldFailWhenAssertingThatNoExceptionShouldBeThrownButThereIs" duration-ms="5" started-at="2016-05-29T19:11:43Z" finished-at="2016-05-29T19:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldFailWhenAssertingThatNoExceptionShouldBeThrownButThereIs -->
        <test-method status="PASS" signature="shouldNotFailWhenAssertingThatNoExceptionShouldBeThrownAndThereIsNot()[pri:0, instance:com.github.grzesiek_galezowski.test_environment.XAssertSpecification@3a4afd8d]" name="shouldNotFailWhenAssertingThatNoExceptionShouldBeThrownAndThereIsNot" duration-ms="1" started-at="2016-05-29T19:11:43Z" finished-at="2016-05-29T19:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldNotFailWhenAssertingThatNoExceptionShouldBeThrownAndThereIsNot -->
        <test-method status="PASS" signature="shouldPerformMutabilityChecksCorrectly()[pri:0, instance:com.github.grzesiek_galezowski.test_environment.XAssertSpecification@3a4afd8d]" name="shouldPerformMutabilityChecksCorrectly" duration-ms="370" started-at="2016-05-29T19:11:43Z" finished-at="2016-05-29T19:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shouldPerformMutabilityChecksCorrectly -->
      </class> <!-- com.github.grzesiek_galezowski.test_environment.XAssertSpecification -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
